ThesaurusShop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from buyer import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_view),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'activate/', views.activateuser, name="activate"),
    url(r'notauthorised/$', views.notauthorized, name="notauthorised"),
    url(r'notlogin/$', views.notlogin, name="notlogin"),
    url(r'^buyer/', include('buyer.urls')),
    url(r'^manager/', include('manager.urls')),
    url(r'^shopkeeper/', include('shopkeeper.urls')),


]

buyer/urls.py
from django.conf.urls import url
from buyer import views

app_name = 'buyer'

urlpatterns = [

    url(r'^$', views.home_view, name="home"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'buyerdashboard',views.buyredashboard_view,name="buyerdashboard"),

]

manager/urls.py
from django.conf.urls import url
from manager import views

app_name = 'manager'

urlpatterns = [
    url(r'^$', views.manager_view),
    url(r'changepassword', views.change_password_view, name= "changepassword"),
    url(r'producttype', views.producttype_view, name="producttype"),
    url(r'category', views.productcategory_view, name="category"),
    url(r'brand', views.productbrand_view, name="brand"),
    url(r'size',views.productsize_view, name="size")
    ]

shopkeeper/urls.py
from django.conf.urls import url
from shopkeeper import views

app_name = 'shopkeeper'

urlpatterns = [
    url(r'^$', views.shopkeeper_index_view),
    url(r'addproduct', views.addproduct_view, name="addproduct"),
    ]

templates/adminmaster.html
<!DOCTYPE HTML>
<html>
<head>
<title>S A T Admin Panel an Admin Panel Category Flat Bootstrap Responsive Website Template | Home :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Novus Admin Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Bootstrap Core CSS -->
<link href="/assets/adminassets/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- Custom CSS -->
<link href="/assets/adminassets/css/style.css" rel='stylesheet' type='text/css' />
<!-- font CSS -->
<!-- font-awesome icons -->
<link href="/assets/adminassets/css/font-awesome.css" rel="stylesheet">
<!-- //font-awesome icons -->
 <!-- js-->
<script src="/assets/adminassets/js/jquery-1.11.1.min.js"></script>
<script src="/assets/adminassets/js/modernizr.custom.js"></script>
<!--webfonts-->
<link href='/assets/adminassets//fonts.googleapis.com/css?family=Roboto+Condensed:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>
<!--//webfonts-->
<!--animate-->
<link href="/assets/adminassets/css/animate.css" rel="stylesheet" type="text/css" media="all">
<script src="/assets/adminassets/js/wow.min.js"></script>
	<script>
		 new WOW().init();
	</script>
<!--//end-animate-->
<!-- chart -->
<script src="/assets/adminassets/js/Chart.js"></script>
<!-- //chart -->
<!--Calender-->
<link rel="stylesheet" href="/assets/adminassets/css/clndr.css" type="text/css" />
<script src="/assets/adminassets/js/underscore-min.js" type="text/javascript"></script>
<script src= "/assets/adminassets/js/moment-2.2.1.js" type="text/javascript"></script>
<script src="/assets/adminassets/js/clndr.js" type="text/javascript"></script>
<script src="/assets/adminassets/js/site.js" type="text/javascript"></script>
<!--End Calender-->
<!-- Metis Menu -->
<script src="/assets/adminassets/js/metisMenu.min.js"></script>
<script src="/assets/adminassets/js/custom.js"></script>
<link href="/assets/adminassets/css/custom.css" rel="stylesheet">
<!--//Metis Menu -->
</head>
<body class="cbp-spmenu-push">
	<div class="main-content">
		<!--left-fixed -navigation-->
		<div class=" sidebar" role="navigation">
            <div class="navbar-collapse">
				<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
					{% if request.session.roleid == 1 %}
					<ul class="nav" id="side-menu">
						<li>
							<a href="index.html" class="active"><i class="fa fa-home nav_icon"></i>Dashboard</a>
						</li>
						<li class="">
							<a href="{% url 'manager:producttype' %}"><i class="fa fa-book nav_icon"></i>Add Type <span class="fa arrow"></span></a>
						</li>
						<li>
							<a href="{% url 'manager:category' %}"><i class="fa fa-th-large nav_icon"></i>Add Category <span class="nav-badge-btm"></span></a>
						</li>
						<li>
							<a href="{% url 'manager:brand' %}"><i class="fa fa-th-large nav_icon"></i>Add Brand <span class="nav-badge-btm"></span></a>
						</li>
						<li>
							<a href="{% url 'manager:size' %}"><i class="fa fa-th-large nav_icon"></i>Add Size <span class="nav-badge-btm"></span></a>
						</li>
					</ul>
					{% elif request.session.roleid == 2 %}
					<ul class="nav">
						<li>
							<a href="index.html" class="active"><i class="fa fa-home nav_icon"></i>Dashboard</a>
						</li>
						<li class="">
							<a href="{% url 'shopkeeper:addproduct' %}"><i class="fa fa-book nav_icon"></i>Add Product <span class="fa arrow"></span></a>
						</li>

					</ul>
					{% endif %}
					<!-- //sidebar-collapse -->
				</nav>
			</div>
		</div>
		<!--left-fixed -navigation-->
		<!-- header-starts -->
		<div class="sticky-header header-section ">
			<div class="header-left">
				<!--toggle button start-->
				<button id="showLeftPush"><i class="fa fa-bars"></i></button>
				<!--toggle button end-->
				<!--logo -->
				<div class="logo">
					<a href="index.html">
						<h1>S A T</h1>
						<span>AdminPanel</span>
					</a>
				</div>
				<!--//logo-->
				<!--search-box-->
				<div class="search-box">
					<form class="input">
						<input class="sb-search-input input__field--madoka" placeholder="Search..." type="search" id="input-31" />
						<label class="input__label" for="input-31">
							<svg class="graphic" width="100%" height="100%" viewBox="0 0 404 77" preserveAspectRatio="none">
								<path d="m0,0l404,0l0,77l-404,0l0,-77z"/>
							</svg>
						</label>
					</form>
				</div><!--//end-search-box-->
				<div class="clearfix"> </div>
			</div>
			<div class="header-right">
				<div class="profile_details_left"><!--notifications of menu start -->
					<ul class="nofitications-dropdown">
						<li class="dropdown head-dpdn">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
							<ul class="dropdown-menu">
								<li>
									<div class="notification_header">
										<h3>You have 3 new messages</h3>
									</div>
								</li>
								<li><a href="#">
								   <div class="user_img"><img src="/assets/adminassets/images/1.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet</p>
									<p><span>1 hour ago</span></p>
									</div>
								   <div class="clearfix"></div>
								</a></li>
								<li class="odd"><a href="#">
									<div class="user_img"><img src="/assets/adminassets/images/2.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet </p>
									<p><span>1 hour ago</span></p>
									</div>
								  <div class="clearfix"></div>
								</a></li>
								<li><a href="#">
								   <div class="user_img"><img src="/assets/adminassets/images/3.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet </p>
									<p><span>1 hour ago</span></p>
									</div>
								   <div class="clearfix"></div>
								</a></li>
								<li>
									<div class="notification_bottom">
										<a href="#">See all messages</a>
									</div>
								</li>
							</ul>
						</li>
						<li class="dropdown head-dpdn">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">3</span></a>
							<ul class="dropdown-menu">
								<li>
									<div class="notification_header">
										<h3>You have 3 new notification</h3>
									</div>
								</li>
								<li><a href="#">
									<div class="user_img"><img src="/assets/adminassets/images/2.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet</p>
									<p><span>1 hour ago</span></p>
									</div>
								  <div class="clearfix"></div>
								 </a></li>
								 <li class="odd"><a href="#">
									<div class="user_img"><img src="/assets/adminassets/images/1.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet </p>
									<p><span>1 hour ago</span></p>
									</div>
								   <div class="clearfix"></div>
								 </a></li>
								 <li><a href="#">
									<div class="user_img"><img src="/assets/adminassets/images/3.png" alt=""></div>
								   <div class="notification_desc">
									<p>Lorem ipsum dolor amet </p>
									<p><span>1 hour ago</span></p>
									</div>
								   <div class="clearfix"></div>
								 </a></li>
								 <li>
									<div class="notification_bottom">
										<a href="#">See all notifications</a>
									</div>
								</li>
							</ul>
						</li>
						<li class="dropdown head-dpdn">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-tasks"></i><span class="badge blue1">15</span></a>
							<ul class="dropdown-menu">
								<li>
									<div class="notification_header">
										<h3>You have 8 pending task</h3>
									</div>
								</li>
								<li><a href="#">
									<div class="task-info">
										<span class="task-desc">Database update</span><span class="percentage">40%</span>
										<div class="clearfix"></div>
									</div>
									<div class="progress progress-striped active">
										<div class="bar yellow" style="width:40%;"></div>
									</div>
								</a></li>
								<li><a href="#">
									<div class="task-info">
										<span class="task-desc">Dashboard done</span><span class="percentage">90%</span>
									   <div class="clearfix"></div>
									</div>
									<div class="progress progress-striped active">
										 <div class="bar green" style="width:90%;"></div>
									</div>
								</a></li>
								<li><a href="#">
									<div class="task-info">
										<span class="task-desc">Mobile App</span><span class="percentage">33%</span>
										<div class="clearfix"></div>
									</div>
								   <div class="progress progress-striped active">
										 <div class="bar red" style="width: 33%;"></div>
									</div>
								</a></li>
								<li><a href="#">
									<div class="task-info">
										<span class="task-desc">Issues fixed</span><span class="percentage">80%</span>
									   <div class="clearfix"></div>
									</div>
									<div class="progress progress-striped active">
										 <div class="bar  blue" style="width: 80%;"></div>
									</div>
								</a></li>
								<li>
									<div class="notification_bottom">
										<a href="#">See all pending tasks</a>
									</div>
								</li>
							</ul>
						</li>
					</ul>
					<div class="clearfix"> </div>
				</div>
				<!--notification menu end -->
				<div class="profile_details">
					<ul>
						<li class="dropdown profile_details_drop">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
								<div class="profile_img">
									<span class="prfil-img"><img src="/assets/adminassets/images/a.png" alt=""> </span>
									<div class="user-name">
										<p>Wikolia</p>
										<span>Administrator</span>
									</div>
									<i class="fa fa-angle-down lnr"></i>
									<i class="fa fa-angle-up lnr"></i>
									<div class="clearfix"></div>
								</div>
							</a>
							<ul class="dropdown-menu drp-mnu">
								<li><a href="#"> <i class="fa fa-cog"></i> Settings</a> </li>
								<li> <a href="#"><i class="fa fa-user"></i> Profile </a></li>
								<li><a href="{% url 'manager:changepassword' %}"> <i class="glyphicon glyphicon-pencil"></i> Change password</a> </li>
								<li> <a href="/logout/"><i class="fa fa-sign-out"></i> Logout</a> </li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<!-- //header-ends -->
		<!-- main content start-->
		<div style="min-height: 574px;" id="page-wrapper">

		{% block content %}

    {% endblock %}
		</div>
		<!--footer-->
		<div class="footer">
		   <p>&copy; 2019 S A T Admin Panel. All Rights Reserved</p>
		</div>
        <!--//footer-->
	</div>
	<!-- Classie -->
		<script src="/assets/adminassets/js/classie.js"></script>
		<script>
			var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
				showLeftPush = document.getElementById( 'showLeftPush' ),
				body = document.body;

			showLeftPush.onclick = function() {
				classie.toggle( this, 'active' );
				classie.toggle( body, 'cbp-spmenu-push-toright' );
				classie.toggle( menuLeft, 'cbp-spmenu-open' );
				disableOther( 'showLeftPush' );
			};


			function disableOther( button ) {
				if( button !== 'showLeftPush' ) {
					classie.toggle( showLeftPush, 'disabled' );
				}
			};
		</script>

	<!--scrolling js-->
	<script src="/assets/adminassets/js/jquery.nicescroll.js"></script>
	<script src="/assets/adminassets/js/scripts.js"></script>
	<!--//scrolling js-->
	<!-- Bootstrap Core JavaScript -->
   <script src="/assets/adminassets/js/bootstrap.js"> </script>
<a href="/">back</a>
</body>
</html>

templates/login.html
{% extends 'buyermaster.html' %}
{% block content %}

<div class="login">
				<div class="main-agileits">
					<div class="form-w3agile">
						<h3>Login To S A T</h3>
						<form  method="post">
							{% csrf_token %}
							{% if wronguname %}
							<script>alert('wrong email id');</script>
							{% endif %}
							{% if wrongpassword %}
							<script>alert('wrong PASSWORD');</script>
							{% endif %}
							<div class="key">
								<i class="fa fa-envelope" aria-hidden="true"></i>
								<input type="text"  name="logintxtemail" id="logintxtemail">
								<div class="clearfix"></div>
							</div>
							<div class="key">
								<i class="fa fa-lock" aria-hidden="true"></i>
								<input type="password" value="Password" name="logintxtpassword" required="">
								<div class="clearfix"></div>
							</div>
							<input type="submit" value="Login">
						</form>
					</div>
					<div class="forg">
						<a href="#" class="forg-left">Forgot Password</a>
						<a href="{% url 'buyer:signup' %}" class="forg-right">Register</a>
						<div class="clearfix"></div>
				</div>
				</div>
	</div>
{% endblock %}

templates/notauthorised.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<style>
body, html {
  height: 100%;
  margin: 0;
}

.bg {
  background-image: url("assets/images/not_authorized.jpg");

  height: 100%;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
</head>

<body>
<div class="bg">

</div>

</body>
</html>

templates/notlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>you need to login first</h1>

</body>
</html>